-- ============================================================================
-- MIGRATION : Phase 19 — Open Elective Management
-- PURPOSE   : Add the four tables Phase 19 could not proceed without —
--             offerings, eligibility rules, student preferences and allocation
--             verdicts — plus their three enums.
--
-- PURELY ADDITIVE, AND VERIFIED SO
--   Every statement CREATEs a new object or constrains one of the four new
--   tables. No existing table is modified: no column added or dropped, no
--   constraint changed, no index rebuilt, no type altered. The back-relations
--   this introduces on Course, Semester, Department, EvaluationScheme, User,
--   Programme, Specialisation, Student and CourseRegistration are virtual in
--   Prisma and emit no DDL.
--
--   Machine-checked before this file was written:
--     grep '^ALTER TABLE' | grep -v '"OpenElective'  ->  0
--
--   Generated by `prisma migrate diff`, not hand-written, so it cannot
--   disagree with the schema it was derived from.
--
-- TENANT ISOLATION IS STRUCTURAL HERE
--   OpenElectiveOffering carries @@unique([tenantId, id]), so the three child
--   tables reference it through a COMPOSITE foreign key on (tenantId, id).
--   A child row citing another tenant's offering is therefore rejected by the
--   database rather than by a predicate a query could forget. The offering's
--   own evaluationScheme reference is composite for the same reason.
--
--   This is stronger than Phase 18's Achievement table, whose parent (Student)
--   lacks the key and could not be given one without altering an existing
--   table. Here the parent is new, so the stronger pattern was available.
--
-- LOCK PROFILE
--   CREATE TABLE and CREATE INDEX on brand-new empty tables take no lock a
--   concurrent reader can observe. Each ADD CONSTRAINT ... FOREIGN KEY takes a
--   SHARE ROW EXCLUSIVE on the referenced table for the length of the
--   statement and validates against zero rows, because the referencing tables
--   are empty. Safe to apply on a live database.
--
-- REVERSIBILITY
--   DROP TABLE "OpenElectiveAllocation", "OpenElectivePreference",
--              "OpenElectiveEligibility", "OpenElectiveOffering";
--   DROP TYPE  "ElectiveAllocationOutcome", "ElectiveAllocationStrategy",
--              "OpenElectiveStatus";
--   Nothing else was changed, so nothing else needs undoing.
-- ============================================================================


-- CreateEnum
CREATE TYPE "OpenElectiveStatus" AS ENUM ('DRAFT', 'OPEN', 'LOCKED', 'ALLOCATED');

-- CreateEnum
CREATE TYPE "ElectiveAllocationStrategy" AS ENUM ('FCFS', 'MERIT');

-- CreateEnum
CREATE TYPE "ElectiveAllocationOutcome" AS ENUM ('ALLOCATED', 'NOT_ALLOCATED');

-- CreateTable
CREATE TABLE "OpenElectiveOffering" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "courseId" TEXT NOT NULL,
    "semesterId" TEXT NOT NULL,
    "offeringDepartmentId" TEXT NOT NULL,
    "evaluationSchemeId" TEXT NOT NULL,
    "totalSeats" INTEGER NOT NULL,
    "status" "OpenElectiveStatus" NOT NULL DEFAULT 'DRAFT',
    "allocationStrategy" "ElectiveAllocationStrategy" NOT NULL DEFAULT 'FCFS',
    "statusChangedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OpenElectiveOffering_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OpenElectiveEligibility" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "offeringId" TEXT NOT NULL,
    "programmeId" TEXT,
    "specialisationId" TEXT,
    "semesterNumber" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OpenElectiveEligibility_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OpenElectivePreference" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "offeringId" TEXT NOT NULL,
    "semesterId" TEXT NOT NULL,
    "preferenceRank" INTEGER NOT NULL,
    "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OpenElectivePreference_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OpenElectiveAllocation" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "offeringId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "preferenceRank" INTEGER NOT NULL,
    "outcome" "ElectiveAllocationOutcome" NOT NULL,
    "courseRegistrationId" TEXT,
    "allocatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OpenElectiveAllocation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "OpenElectiveOffering_tenantId_semesterId_status_idx" ON "OpenElectiveOffering"("tenantId", "semesterId", "status");

-- CreateIndex
CREATE INDEX "OpenElectiveOffering_offeringDepartmentId_idx" ON "OpenElectiveOffering"("offeringDepartmentId");

-- CreateIndex
CREATE UNIQUE INDEX "OpenElectiveOffering_courseId_semesterId_key" ON "OpenElectiveOffering"("courseId", "semesterId");

-- CreateIndex
CREATE UNIQUE INDEX "OpenElectiveOffering_tenantId_id_key" ON "OpenElectiveOffering"("tenantId", "id");

-- CreateIndex
CREATE INDEX "OpenElectiveEligibility_tenantId_offeringId_idx" ON "OpenElectiveEligibility"("tenantId", "offeringId");

-- CreateIndex
CREATE INDEX "OpenElectiveEligibility_programmeId_idx" ON "OpenElectiveEligibility"("programmeId");

-- CreateIndex
CREATE INDEX "OpenElectiveEligibility_specialisationId_idx" ON "OpenElectiveEligibility"("specialisationId");

-- CreateIndex
CREATE INDEX "OpenElectivePreference_tenantId_offeringId_preferenceRank_s_idx" ON "OpenElectivePreference"("tenantId", "offeringId", "preferenceRank", "submittedAt");

-- CreateIndex
CREATE UNIQUE INDEX "OpenElectivePreference_studentId_offeringId_key" ON "OpenElectivePreference"("studentId", "offeringId");

-- CreateIndex
CREATE UNIQUE INDEX "OpenElectivePreference_studentId_semesterId_preferenceRank_key" ON "OpenElectivePreference"("studentId", "semesterId", "preferenceRank");

-- CreateIndex
CREATE INDEX "OpenElectiveAllocation_tenantId_offeringId_outcome_idx" ON "OpenElectiveAllocation"("tenantId", "offeringId", "outcome");

-- CreateIndex
CREATE INDEX "OpenElectiveAllocation_studentId_idx" ON "OpenElectiveAllocation"("studentId");

-- CreateIndex
CREATE INDEX "OpenElectiveAllocation_courseRegistrationId_idx" ON "OpenElectiveAllocation"("courseRegistrationId");

-- CreateIndex
CREATE UNIQUE INDEX "OpenElectiveAllocation_offeringId_studentId_key" ON "OpenElectiveAllocation"("offeringId", "studentId");

-- AddForeignKey
ALTER TABLE "OpenElectiveOffering" ADD CONSTRAINT "OpenElectiveOffering_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "OpenElectiveOffering" ADD CONSTRAINT "OpenElectiveOffering_semesterId_fkey" FOREIGN KEY ("semesterId") REFERENCES "Semester"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "OpenElectiveOffering" ADD CONSTRAINT "OpenElectiveOffering_offeringDepartmentId_fkey" FOREIGN KEY ("offeringDepartmentId") REFERENCES "Department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "OpenElectiveOffering" ADD CONSTRAINT "OpenElectiveOffering_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpenElectiveOffering" ADD CONSTRAINT "OpenElectiveOffering_tenantId_evaluationSchemeId_fkey" FOREIGN KEY ("tenantId", "evaluationSchemeId") REFERENCES "EvaluationScheme"("tenantId", "id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "OpenElectiveEligibility" ADD CONSTRAINT "OpenElectiveEligibility_tenantId_offeringId_fkey" FOREIGN KEY ("tenantId", "offeringId") REFERENCES "OpenElectiveOffering"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpenElectiveEligibility" ADD CONSTRAINT "OpenElectiveEligibility_programmeId_fkey" FOREIGN KEY ("programmeId") REFERENCES "Programme"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpenElectiveEligibility" ADD CONSTRAINT "OpenElectiveEligibility_specialisationId_fkey" FOREIGN KEY ("specialisationId") REFERENCES "Specialisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpenElectivePreference" ADD CONSTRAINT "OpenElectivePreference_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpenElectivePreference" ADD CONSTRAINT "OpenElectivePreference_tenantId_offeringId_fkey" FOREIGN KEY ("tenantId", "offeringId") REFERENCES "OpenElectiveOffering"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpenElectiveAllocation" ADD CONSTRAINT "OpenElectiveAllocation_tenantId_offeringId_fkey" FOREIGN KEY ("tenantId", "offeringId") REFERENCES "OpenElectiveOffering"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpenElectiveAllocation" ADD CONSTRAINT "OpenElectiveAllocation_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpenElectiveAllocation" ADD CONSTRAINT "OpenElectiveAllocation_courseRegistrationId_fkey" FOREIGN KEY ("courseRegistrationId") REFERENCES "CourseRegistration"("id") ON DELETE SET NULL ON UPDATE CASCADE;

