-- ============================================================================
-- MIGRATION : Phase 20 — Faculty Feedback System
-- PURPOSE   : Add the metadata-driven questionnaire — forms, questions,
--             submissions and answers — plus their three enums.
--
-- PURELY ADDITIVE, AND VERIFIED SO
--   Every statement CREATEs a new object or constrains one of the four new
--   tables. No existing table is modified: no column added or dropped, no
--   constraint changed, no index rebuilt, no type altered. The back-relations
--   introduced on FacultyMember, Course, Semester, Student and User are virtual
--   in Prisma and emit no DDL.
--
--   Machine-checked before this file was written:
--     grep '^ALTER TABLE' | grep -v '"Feedback'  ->  0
--
--   Generated by `prisma migrate diff`, not hand-written, so it cannot disagree
--   with the schema it was derived from.
--
-- NO FIXED RATING COLUMNS
--   "Teaching", "Behaviour", "Communication", "Practical Knowledge" and
--   "Infrastructure" appear nowhere as columns. They are FeedbackCategory
--   values against which a tenant writes its own questions, so a university
--   adding a ninth dimension configures a row rather than requesting a
--   migration.
--
-- TENANT ISOLATION IS STRUCTURAL WHERE IT COULD BE
--   FeedbackForm and FeedbackSubmission carry @@unique([tenantId, id]), so
--   questions and answers reference them through COMPOSITE foreign keys on
--   (tenantId, id) — a child citing another tenant's parent is refused by the
--   database rather than by a predicate a query could forget.
--
--   References to PRE-EXISTING models (Student, FacultyMember, Course,
--   Semester) are plain single-column foreign keys with tenantId carried
--   alongside, because none of those parents has the composite key and adding
--   one would alter an existing table. Cross-tenant consistency there is
--   enforced by the repository. That is a stated weakening, not an oversight.
--
-- LOCK PROFILE
--   CREATE TABLE and CREATE INDEX on brand-new empty tables take no lock a
--   concurrent reader can observe. Each ADD CONSTRAINT ... FOREIGN KEY takes a
--   SHARE ROW EXCLUSIVE on the referenced table for the length of the statement
--   and validates against zero rows. Safe to apply on a live database.
--
-- REVERSIBILITY
--   DROP TABLE "FeedbackAnswer", "FeedbackSubmission", "FeedbackQuestion",
--              "FeedbackForm";
--   DROP TYPE  "FeedbackSubmissionStatus", "FeedbackCategory",
--              "FeedbackFormStatus";
-- ============================================================================


-- CreateEnum
CREATE TYPE "FeedbackFormStatus" AS ENUM ('DRAFT', 'OPEN', 'CLOSED');

-- CreateEnum
CREATE TYPE "FeedbackCategory" AS ENUM ('TEACHING', 'BEHAVIOUR', 'COMMUNICATION', 'PRACTICAL_KNOWLEDGE', 'INFRASTRUCTURE', 'LAB_EXPERIENCE', 'OVERALL');

-- CreateEnum
CREATE TYPE "FeedbackSubmissionStatus" AS ENUM ('DRAFT', 'SUBMITTED');

-- CreateTable
CREATE TABLE "FeedbackForm" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "FeedbackFormStatus" NOT NULL DEFAULT 'DRAFT',
    "sessionType" "SessionType" NOT NULL DEFAULT 'LECTURE',
    "createdById" TEXT,
    "statusChangedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FeedbackForm_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FeedbackQuestion" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "formId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "category" "FeedbackCategory" NOT NULL,
    "weight" DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    "sequence" INTEGER NOT NULL,
    "isRequired" BOOLEAN NOT NULL DEFAULT true,
    "allowsComment" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FeedbackQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FeedbackSubmission" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "formId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "facultyId" TEXT NOT NULL,
    "courseId" TEXT NOT NULL,
    "semesterId" TEXT NOT NULL,
    "status" "FeedbackSubmissionStatus" NOT NULL DEFAULT 'DRAFT',
    "submittedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FeedbackSubmission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FeedbackAnswer" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "submissionId" TEXT NOT NULL,
    "questionId" TEXT NOT NULL,
    "rating" SMALLINT NOT NULL,
    "comment" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FeedbackAnswer_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "FeedbackForm_tenantId_status_sessionType_idx" ON "FeedbackForm"("tenantId", "status", "sessionType");

-- CreateIndex
CREATE UNIQUE INDEX "FeedbackForm_tenantId_code_version_key" ON "FeedbackForm"("tenantId", "code", "version");

-- CreateIndex
CREATE UNIQUE INDEX "FeedbackForm_tenantId_id_key" ON "FeedbackForm"("tenantId", "id");

-- CreateIndex
CREATE INDEX "FeedbackQuestion_tenantId_formId_sequence_idx" ON "FeedbackQuestion"("tenantId", "formId", "sequence");

-- CreateIndex
CREATE UNIQUE INDEX "FeedbackQuestion_formId_code_key" ON "FeedbackQuestion"("formId", "code");

-- CreateIndex
CREATE INDEX "FeedbackSubmission_tenantId_facultyId_courseId_semesterId_s_idx" ON "FeedbackSubmission"("tenantId", "facultyId", "courseId", "semesterId", "status");

-- CreateIndex
CREATE INDEX "FeedbackSubmission_tenantId_formId_status_idx" ON "FeedbackSubmission"("tenantId", "formId", "status");

-- CreateIndex
CREATE INDEX "FeedbackSubmission_studentId_idx" ON "FeedbackSubmission"("studentId");

-- CreateIndex
CREATE UNIQUE INDEX "FeedbackSubmission_studentId_facultyId_courseId_semesterId__key" ON "FeedbackSubmission"("studentId", "facultyId", "courseId", "semesterId", "formId");

-- CreateIndex
CREATE UNIQUE INDEX "FeedbackSubmission_tenantId_id_key" ON "FeedbackSubmission"("tenantId", "id");

-- CreateIndex
CREATE INDEX "FeedbackAnswer_tenantId_submissionId_idx" ON "FeedbackAnswer"("tenantId", "submissionId");

-- CreateIndex
CREATE INDEX "FeedbackAnswer_questionId_idx" ON "FeedbackAnswer"("questionId");

-- CreateIndex
CREATE UNIQUE INDEX "FeedbackAnswer_submissionId_questionId_key" ON "FeedbackAnswer"("submissionId", "questionId");

-- AddForeignKey
ALTER TABLE "FeedbackForm" ADD CONSTRAINT "FeedbackForm_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeedbackQuestion" ADD CONSTRAINT "FeedbackQuestion_tenantId_formId_fkey" FOREIGN KEY ("tenantId", "formId") REFERENCES "FeedbackForm"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeedbackSubmission" ADD CONSTRAINT "FeedbackSubmission_tenantId_formId_fkey" FOREIGN KEY ("tenantId", "formId") REFERENCES "FeedbackForm"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeedbackSubmission" ADD CONSTRAINT "FeedbackSubmission_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeedbackSubmission" ADD CONSTRAINT "FeedbackSubmission_facultyId_fkey" FOREIGN KEY ("facultyId") REFERENCES "FacultyMember"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "FeedbackSubmission" ADD CONSTRAINT "FeedbackSubmission_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "FeedbackSubmission" ADD CONSTRAINT "FeedbackSubmission_semesterId_fkey" FOREIGN KEY ("semesterId") REFERENCES "Semester"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "FeedbackAnswer" ADD CONSTRAINT "FeedbackAnswer_tenantId_submissionId_fkey" FOREIGN KEY ("tenantId", "submissionId") REFERENCES "FeedbackSubmission"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeedbackAnswer" ADD CONSTRAINT "FeedbackAnswer_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "FeedbackQuestion"("id") ON DELETE CASCADE ON UPDATE CASCADE;

