import type { ReactNode } from "react";
import { redirect } from "next/navigation";
import { PortalShell } from "@/components/layout/PortalShell";
import { PLATFORM_NAV, filterNav } from "@/constants/navigation";
import { getPlatformSession } from "@/lib/auth/platformSession";
import { requirePlatformAdmin } from "@/lib/middleware/requirePlatformAdmin";
import { getPlatformUser } from "@/lib/services/platformUser.service";
import { accentAttribute, resolveAccent } from "@/lib/constants/platformAccent";

/**
 * Platform Admin portal — the tenant onboarding and billing console.
 *
 * WHAT CHANGED IN W1.2, AND WHY IT HAD TO
 *   This layout used to admit anyone whose TENANT session carried a role named
 *   "SUPER_ADMIN". The W1.1 audit reproduced a university admin granting
 *   themselves exactly that role and reading every tenant on the platform.
 *
 *   It now reads the PLATFORM session — a credential minted only by
 *   /api/super-admin/auth/login, only after a PlatformUser authenticates.
 *   PlatformUser has no tenantId, so no tenant operation can produce one. A
 *   tenant session, whatever roles it claims, does not reach this screen.
 *
 * THE GUARD IS RE-RUN AGAINST THE DATABASE, NOT INFERRED FROM THE COOKIE
 *   requirePlatformAdmin re-reads PlatformUserRole and isActive on every
 *   request, so a revoked operator loses the console immediately rather than
 *   when their token happens to expire. This layout and every /api/platform
 *   route run the same function, so the screen and the data agree by
 *   construction.
 *
 * A Server Component, which is what makes this meaningful: a caller without a
 * platform session never receives the page's markup at all.
 */
export default async function PlatformLayout({ children }: { children: ReactNode }) {
  const guard = await requirePlatformAdmin();

  if (!guard.authorized) {
    // W1.3 — an operator whose password was generated by somebody else is sent
    // to change it, not to sign in again. Signing in again is what they just
    // did; it cannot resolve this, and returning them to the login form with a
    // working session is how a user concludes the console is broken.
    //
    // The guard is what makes this a gate rather than a suggestion: it refuses
    // every /api/platform route in the same state, so skipping this screen by
    // typing a URL yields a console with no data in it.
    if (guard.reason === "PASSWORD_CHANGE_REQUIRED") redirect("/super-admin/change-password");

    // Sent to the platform sign-in, NOT to /login. A platform operator has no
    // university and no tenant slug to supply, so the tenant login form cannot
    // authenticate them.
    redirect("/super-admin/login");
  }

  const session = await getPlatformSession();

  // Unreachable — the guard above already proved a session exists. Narrowed
  // rather than asserted so a future change to the guard cannot silently
  // produce a null read here.
  if (!session) redirect("/super-admin/login");

  // THIS operator's accent, read from their own PlatformUser row. resolveAccent
  // turns null — and anything the application no longer recognises — into
  // DEFAULT, so a malformed preference renders the console it always did rather
  // than breaking it.
  //
  // A failed read is not an error state here: the console is not about
  // appearance, and refusing to render it because a colour could not be
  // resolved would be the wrong trade. It falls back to the default.
  const operator = await getPlatformUser(guard.platformUserId);
  const accent = resolveAccent(operator?.accentColor);

  return (
    // The ONLY element in the application carrying this attribute, and the only
    // place the accent is applied. CSS custom properties inherit, so the blocks
    // in globals.css reach this subtree — the platform console — and nothing
    // else. :root is untouched, so every tenant portal keeps resolving --primary
    // exactly as before.
    //
    // DEFAULT emits no attribute at all (accentAttribute returns undefined), so
    // an operator who never chose renders a DOM identical to the one before this
    // feature existed.
    <div data-platform-accent={accentAttribute(accent)} className="contents">
      <PortalShell
        // No notification bell: the Notification Centre is tenant-scoped, and a
        // platform operator belongs to no tenant. Rendering it would issue a
        // request that can only ever answer 401.
        sections={filterNav(PLATFORM_NAV, ["PLATFORM_ADMIN"])}
        user={{
          name: session.email,
          email: session.email,
          roleLabel: "Platform Admin",
        }}
        portalName="Platform"
        homeHref="/platform/dashboard"
        // NOT /settings. That screen resolves its subject through
        // getPortalSession() and reads a User row, a profile and notification
        // preferences — all tenant records. A PlatformUser has none of them, so
        // the account layout found no tenant session and redirected here to
        // /login, which reads as being signed out despite edu_platform still
        // being valid.
        //
        // The operator's own account screen. It lives in THIS route group, so it
        // is guarded by the same requirePlatformAdmin() as every other console
        // page and renders inside the same chrome — a tenant session never
        // reaches it. /super-admin/change-password still exists and still serves
        // the forced-change flow; this page reuses its form for the voluntary one.
        settingsHref="/super-admin/settings"
        // The console's own sign-out. The default clears the TENANT cookies,
        // which a platform operator does not hold — it answered 200 and left
        // edu_platform valid, so the top bar reported signing out while the
        // console stayed open.
        signOut="platform"
      >
        {children}
      </PortalShell>
    </div>
  );
}
