import type { ReactNode } from "react";
import { redirect } from "next/navigation";
import { PortalShell } from "@/components/layout/PortalShell";
import { PLATFORM_NAV, filterNav } from "@/constants/navigation";
import { getPlatformSession } from "@/lib/auth/platformSession";
import { requirePlatformAdmin } from "@/lib/middleware/requirePlatformAdmin";

/**
 * Platform Admin portal — the tenant onboarding and billing console.
 *
 * WHAT CHANGED IN W1.2, AND WHY IT HAD TO
 *   This layout used to admit anyone whose TENANT session carried a role named
 *   "SUPER_ADMIN". The W1.1 audit reproduced a university admin granting
 *   themselves exactly that role and reading every tenant on the platform.
 *
 *   It now reads the PLATFORM session — a credential minted only by
 *   /api/super-admin/auth/login, only after a PlatformUser authenticates.
 *   PlatformUser has no tenantId, so no tenant operation can produce one. A
 *   tenant session, whatever roles it claims, does not reach this screen.
 *
 * THE GUARD IS RE-RUN AGAINST THE DATABASE, NOT INFERRED FROM THE COOKIE
 *   requirePlatformAdmin re-reads PlatformUserRole and isActive on every
 *   request, so a revoked operator loses the console immediately rather than
 *   when their token happens to expire. This layout and every /api/platform
 *   route run the same function, so the screen and the data agree by
 *   construction.
 *
 * A Server Component, which is what makes this meaningful: a caller without a
 * platform session never receives the page's markup at all.
 */
export default async function PlatformLayout({ children }: { children: ReactNode }) {
  const guard = await requirePlatformAdmin();

  if (!guard.authorized) {
    // W1.3 — an operator whose password was generated by somebody else is sent
    // to change it, not to sign in again. Signing in again is what they just
    // did; it cannot resolve this, and returning them to the login form with a
    // working session is how a user concludes the console is broken.
    //
    // The guard is what makes this a gate rather than a suggestion: it refuses
    // every /api/platform route in the same state, so skipping this screen by
    // typing a URL yields a console with no data in it.
    if (guard.reason === "PASSWORD_CHANGE_REQUIRED") redirect("/super-admin/change-password");

    // Sent to the platform sign-in, NOT to /login. A platform operator has no
    // university and no tenant slug to supply, so the tenant login form cannot
    // authenticate them.
    redirect("/super-admin/login");
  }

  const session = await getPlatformSession();

  // Unreachable — the guard above already proved a session exists. Narrowed
  // rather than asserted so a future change to the guard cannot silently
  // produce a null read here.
  if (!session) redirect("/super-admin/login");

  return (
    <PortalShell
      // No notification bell: the Notification Centre is tenant-scoped, and a
      // platform operator belongs to no tenant. Rendering it would issue a
      // request that can only ever answer 401.
      sections={filterNav(PLATFORM_NAV, ["PLATFORM_ADMIN"])}
      user={{
        name: session.email,
        email: session.email,
        roleLabel: "Platform Admin",
      }}
      portalName="Platform"
      homeHref="/platform/dashboard"
      // NOT /settings. That screen resolves its subject through
      // getPortalSession() and reads a User row, a profile and notification
      // preferences — all tenant records. A PlatformUser has none of them, so
      // the account layout found no tenant session and redirected here to
      // /login, which reads as being signed out despite edu_platform still
      // being valid.
      //
      // This is the only page in the project that manages a platform
      // operator's own account: it is guarded by getPlatformSession(), it
      // names the operator it is signed in as, and it returns to the console
      // when it is done. A tenant session reaches it and is sent to the
      // platform sign-in, so it is no wider a door than the console itself.
      settingsHref="/super-admin/change-password"
    >
      {children}
    </PortalShell>
  );
}
